import Head from 'next/head';
import { Container, Main, Title } from './index.styles';

export default function Home() {
  return (
    <Container>
      <Head>
        <title>
          Next.js, TypeScript, Styled-Components, Jest, Testing-Library
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <Title>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </Title>
      </Main>
    </Container>
  );
}
